<?php

echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
echo 'un caricaturist a caricaturizat o caricatura caricaturistica'
php_check_syntax